### ISSUE TITLE
slow htmlfile generation

### ISSUE THREAD

**Issue by misanthropos** [rojenzaman/video-gallery-generator_bash#1]
You could speedup the process by first generating a tmphtml file in /dev/shm for instance and then just move that to its final destination. You will save lots of harddisk accesses from those many cat <<OEF commandos and so speedup the procedure considerably.

**Comment by rojenzaman** [comment]
> You could speedup the process by first generating a tmphtml file in /dev/shm for instance and then just move that to its final destination. You will save lots of harddisk accesses from those many cat <<OEF commandos and so speedup the procedure considerably.

Sounds reasonable, I will implement that.

**Comment by misanthropos** [comment]
I would have supplied a PR, but I have changed your code to my needs.

**Comment by rojenzaman** [comment]
If it points and becomes public, I'd be happy to merge the pull request.

**Comment by misanthropos** [comment]
I stripped some I deemed not needed.

but the idea is to define a tmpindexfile and cat everything to that. 
```
tmpindex=/dev/shm/tmpindex.html
```
and then
```
mv $tmpindex $indexhtml
```

**Comment by rojenzaman** [comment]
I used [pp echo templates](https://adi.onl/pp.html) instead of /dev/shm, because /dev/shm not exists for all systems for example android.

 - [index.pp.html](https://github.com/rojenzaman/video-gallery-generator_bash/blob/master/index.pp.html)
 - [player.pp.html](https://github.com/rojenzaman/video-gallery-generator_bash/blob/master/player.pp.html)

**Comment by misanthropos** [comment]
I do not like the idea to download, extract and execute a program just for that task.
If your connection is slow. It would not matter if you would run the program once for a directory.
In my case however I organize the pictures of a webcam and it has to run every time a new stream was recorded for that day directory. That is when I noticed it was quite slow.
/tmp nowadays is a tmpfs filesystem in RAM and should be available everywhere.
Alternatively you could google for other solutions - maybe sockets. For your case I think your prior solution is better than this.

**Comment by rojenzaman** [comment]
I added some options to the script, maybe it will help you.

help page:

```
Usage: video-gallery-generator.sh [-t <title>] [-d <thumbdir>] [-m] [-e] [-s] [-q] [-h]:
	[-t <title>]	 sets the title (default: Video Gallery)
	[-d <thumbdir>]	 sets the thumbdir (default: video)
	[-m]		 use tmpfs for html generation (default: /dev/shm/vgg-index.html)
	[-e]		 skip print exif data
	[-s]		 skip thumbnail generation
	[-q]		 skip author and title generation
	[-h]		 displays help (this message)
```

**Comment by misanthropos** [comment]
That is a better approach. So with -m I can specify where the temp file will reside? You can even create more generic temp file names with mktmp.

**Comment by misanthropos** [comment]
Anyway. Good idea to make it optional to extract data and/or generate thumbnails. For the moment I am happy with my current installation. Will try it out sometime if I wanted to change something.
